INSERT INTO GENERO (GENERO)  (SELECT DISTINCT GENERO_EMPLEADO FROM temporal );
INSERT INTO DIRECCION (DIRECCION)  SELECT DISTINCT DIRECCION_EMPLEADO FROM temporal;
INSERT INTO DIRECCION (DIRECCION)  SELECT DISTINCT DIRECCION_PACIENTE FROM temporal;
INSERT INTO TITULO_EMPLEADO (TITULO)  SELECT DISTINCT TITULO_DEL_EMPLEADO FROM temporal;
INSERT INTO SINTOMA_PACIENTE (SINTOMA)  SELECT DISTINCT SINTOMA_DEL_PACIENTE FROM temporal;
INSERT INTO TRATAMIENTO_APLICADO (TRATAMIENTO,FECHA_TRATAMIENTO)  SELECT DISTINCT TRATAMIENTO_APLICADO,FECHA_TRATAMIENTO FROM temporal;
INSERT INTO DIAGNOSICO_SINTOMA (DIAGNOSTICO)  SELECT DISTINCT DIAGNOSTICO_DEL_SINTOMA FROM temporal;

INSERT INTO EMPLEADO (NOMBRE_EMPLEADO, APELLIDO_EMPLEADO, TELEFONO_EMPLEADO, GENERO, FECHA_NACIMIENTO, TITULO_EMPLEADO, DIRECCION)
SELECT DISTINCT
                NOMBRE_EMPLEADO,
                APELLIDO_EMPLEADO,
                TELEFONO_EMPLEADO,
                (SELECT ID_GENERO FROM GENERO WHERE GENERO=GENERO_EMPLEADO),
                FECHA_NACIMIENTO_EMPLEADO,
                (SELECT ID_TITULO FROM TITULO_EMPLEADO WHERE TITULO=TITULO_DEL_EMPLEADO),
                (SELECT ID_DIRECCION FROM DIRECCION WHERE DIRECCION=DIRECCION_EMPLEADO)
FROM TEMPORAL;

INSERT INTO PACIENTE (NOMBRE_PACIENTE, APELLIDO_PACIENTE, TELEFONO_PACIENTE, FECHA_NACIMIENTO, PESO, ALTURA, DIRECCION, GENERO)
SELECT
    DISTINCT
    NOMBRE_PACIENTE,
    APELLIDO_PACIENTE,
    TELEFONO_PACIENTE,
    FECHA_NACIMIENTO_PACIENTE,
    PESO,
    ALTURA,
    (SELECT ID_DIRECCION FROM DIRECCION WHERE DIRECCION=DIRECCION_PACIENTE),
    (SELECT ID_GENERO FROM GENERO WHERE GENERO=GENERO_PACIENTE)
FROM TEMPORAL;

INSERT INTO EVALUACION(id_empleado, id_paciente, id_tratamiento_aplicado, id_diagnostico_sintoma, id_sintoma_paciente, fecha_evaluacion, rango_diagnostico)
SELECT
       DISTINCT
    (SELECT ID_EMPLEADO FROM EMPLEADO WHERE NOMBRE_EMPLEADO=NOMBRE_EMPLEADO AND APELLIDO_EMPLEADO=APELLIDO_EMPLEADO),
    (SELECT ID_PACIENTE FROM PACIENTE WHERE NOMBRE_PACIENTE=NOMBRE_PACIENTE AND APELLIDO_PACIENTE=APELLIDO_PACIENTE),
    (SELECT ID_TRATAMIENTO FROM TRATAMIENTO_APLICADO WHERE TEMPORAL.TRATAMIENTO_APLICADO = TRATAMIENTO_APLICADO.TRATAMIENTO and TEMPORAL.FECHA_TRATAMIENTO = TRATAMIENTO_APLICADO.FECHA_TRATAMIENTO),
    (SELECT ID_DIAGNOSTICO FROM DIAGNOSICO_SINTOMA WHERE TEMPORAL.DIAGNOSTICO_DEL_SINTOMA = DIAGNOSICO_SINTOMA.DIAGNOSTICO),
    (SELECT ID_SINTOMA FROM SINTOMA_PACIENTE WHERE TEMPORAL.SINTOMA_DEL_PACIENTE = SINTOMA_PACIENTE.SINTOMA),
    FECHA_EVALUACION,
    RANGO_DEL_DIAGNOSTICO
FROM TEMPORAL;

select * from DIRECCION;
select * from TITULO_EMPLEADO;
select * from SINTOMA_PACIENTE;
select * from TRATAMIENTO_APLICADO;
select * from DIAGNOSICO_SINTOMA;
select * from EMPLEADO order by ID_EMPLEADO;
select * from PACIENTE;
select * from EVALUACION;

