INSERT INTO GENERO (GENERO)  (SELECT DISTINCT GENERO_EMPLEADO FROM temporal WHERE GENERO_EMPLEADO IS NOT NULL ) ;
INSERT INTO TITULO_EMPLEADO (TITULO)  SELECT DISTINCT TITULO_DEL_EMPLEADO FROM temporal WHERE TITULO_DEL_EMPLEADO IS NOT NULL ;
INSERT INTO SINTOMA_PACIENTE (SINTOMA)  SELECT DISTINCT SINTOMA_DEL_PACIENTE FROM temporal WHERE SINTOMA_DEL_PACIENTE IS NOT NULL;
INSERT INTO TRATAMIENTO_APLICADO (TRATAMIENTO,FECHA_TRATAMIENTO)  SELECT DISTINCT TRATAMIENTO_APLICADO,FECHA_TRATAMIENTO FROM temporal;
INSERT INTO DIAGNOSICO_SINTOMA (DIAGNOSTICO,RANGO_DIAGNOSTICO)  SELECT DISTINCT DIAGNOSTICO_DEL_SINTOMA,RANGO_DEL_DIAGNOSTICO FROM temporal WHERE RANGO_DEL_DIAGNOSTICO IS NOT NULL AND DIAGNOSTICO_DEL_SINTOMA IS NOT NULL ;

INSERT INTO EMPLEADO (NOMBRE_EMPLEADO, APELLIDO_EMPLEADO, TELEFONO_EMPLEADO, GENERO, FECHA_NACIMIENTO, TITULO_EMPLEADO, DIRECCION_EMPLEADO)
SELECT DISTINCT
                NOMBRE_EMPLEADO,
                APELLIDO_EMPLEADO,
                TELEFONO_EMPLEADO,
                (SELECT ID_GENERO FROM GENERO WHERE GENERO=GENERO_EMPLEADO),
                FECHA_NACIMIENTO_EMPLEADO,
                (SELECT ID_TITULO FROM TITULO_EMPLEADO WHERE TITULO=TITULO_DEL_EMPLEADO),
                DIRECCION_EMPLEADO
FROM TEMPORAL WHERE FECHA_NACIMIENTO_EMPLEADO IS NOT NULL ;

INSERT INTO PACIENTE (NOMBRE_PACIENTE, APELLIDO_PACIENTE, TELEFONO_PACIENTE, FECHA_NACIMIENTO, PESO, ALTURA, GENERO,DIRECCION_PACIENTE)
SELECT
    DISTINCT
    NOMBRE_PACIENTE,
    APELLIDO_PACIENTE,
    TELEFONO_PACIENTE,
    FECHA_NACIMIENTO_PACIENTE,
    PESO,
    ALTURA,
    (SELECT ID_GENERO FROM GENERO WHERE GENERO=GENERO_PACIENTE),
    DIRECCION_PACIENTE
FROM TEMPORAL WHERE NOMBRE_PACIENTE IS NOT NULL;

INSERT INTO EVALUACION(id_empleado, id_paciente, id_tratamiento_aplicado, id_diagnostico_sintoma, id_sintoma_paciente, fecha_evaluacion)
SELECT
       DISTINCT
    (SELECT ID_EMPLEADO FROM EMPLEADO E WHERE E.NOMBRE_EMPLEADO=TEMPORAL.NOMBRE_EMPLEADO AND E.APELLIDO_EMPLEADO=TEMPORAL.APELLIDO_EMPLEADO ),
    (SELECT ID_PACIENTE FROM PACIENTE P WHERE P.NOMBRE_PACIENTE=TEMPORAL.NOMBRE_PACIENTE AND P.APELLIDO_PACIENTE=TEMPORAL.APELLIDO_PACIENTE),
    (SELECT ID_TRATAMIENTO FROM TRATAMIENTO_APLICADO T WHERE TEMPORAL.TRATAMIENTO_APLICADO = T.TRATAMIENTO and TEMPORAL.FECHA_TRATAMIENTO = T.FECHA_TRATAMIENTO),
    (SELECT ID_DIAGNOSTICO FROM DIAGNOSICO_SINTOMA D WHERE TEMPORAL.DIAGNOSTICO_DEL_SINTOMA = D.DIAGNOSTICO AND TEMPORAL.RANGO_DEL_DIAGNOSTICO=D.RANGO_DIAGNOSTICO),
    (SELECT ID_SINTOMA FROM SINTOMA_PACIENTE S WHERE TEMPORAL.SINTOMA_DEL_PACIENTE = S.SINTOMA ),
    FECHA_EVALUACION
FROM TEMPORAL  ;



select * from TITULO_EMPLEADO;
select * from SINTOMA_PACIENTE;
select * from TRATAMIENTO_APLICADO;
select * from DIAGNOSICO_SINTOMA;
select *from EMPLEADO;
select * from PACIENTE;
select * from EVALUACION;
select * FROM GENERO;

