CREATE TABLE GENERO(
    ID_GENERO NUMBER GENERATED ALWAYS AS IDENTITY (start with 1 INCREMENT BY 1) PRIMARY KEY ,
    GENERO CHAR
);
CREATE TABLE TITULO_EMPLEADO(
    ID_TITULO NUMBER GENERATED ALWAYS AS IDENTITY (start with 1 INCREMENT BY 1)  PRIMARY KEY,
    TITULO VARCHAR (50)
);

CREATE TABLE DIAGNOSICO_SINTOMA(
    ID_DIAGNOSTICO NUMBER GENERATED ALWAYS AS IDENTITY (start with 1 INCREMENT BY 1)  PRIMARY KEY ,
    DIAGNOSTICO VARCHAR(50),
    RANGO_DIAGNOSTICO NUMBER
);

CREATE TABLE TRATAMIENTO_APLICADO(
    ID_TRATAMIENTO NUMBER GENERATED ALWAYS AS IDENTITY (start with 1 INCREMENT BY 1)  PRIMARY KEY ,
    TRATAMIENTO VARCHAR(50),
    FECHA_TRATAMIENTO DATE

);
CREATE TABLE SINTOMA_PACIENTE (
    ID_SINTOMA NUMBER GENERATED ALWAYS AS IDENTITY (start with 1 INCREMENT BY 1)  PRIMARY KEY ,
    SINTOMA VARCHAR(50)
);
CREATE TABLE EMPLEADO(
    ID_EMPLEADO NUMBER GENERATED ALWAYS AS IDENTITY (start with 1 INCREMENT BY 1)  PRIMARY KEY ,
    NOMBRE_EMPLEADO VARCHAR(50),
    APELLIDO_EMPLEADO VARCHAR(50),
    TELEFONO_EMPLEADO VARCHAR(50),
    GENERO INTEGER,
    FECHA_NACIMIENTO DATE,
    TITULO_EMPLEADO INTEGER,
    DIRECCION_EMPLEADO VARCHAR(50),
    foreign key (GENERO) references GENERO(ID_GENERO)

);

CREATE TABLE PACIENTE(
    ID_PACIENTE NUMBER GENERATED ALWAYS AS IDENTITY (start with 1 INCREMENT BY 1)  PRIMARY KEY ,
    NOMBRE_PACIENTE VARCHAR(50),
    APELLIDO_PACIENTE VARCHAR(50),
    TELEFONO_PACIENTE VARCHAR(50),
    FECHA_NACIMIENTO DATE,
    PESO NUMBER,
    ALTURA NUMBER,
    GENERO INTEGER,
    DIRECCION_PACIENTE VARCHAR(50),
    foreign key (GENERO) references GENERO(ID_GENERO)

);

CREATE TABLE EVALUACION(
    ID_EVALUCACION NUMBER GENERATED ALWAYS AS IDENTITY (start with 1 INCREMENT BY 1)  PRIMARY KEY ,
    ID_EMPLEADO INTEGER,
    ID_PACIENTE INTEGER,
    ID_TRATAMIENTO_APLICADO INTEGER,
    ID_DIAGNOSTICO_SINTOMA INTEGER,
    ID_SINTOMA_PACIENTE INTEGER,
    FECHA_EVALUACION DATE,
    foreign key (ID_EMPLEADO) references EMPLEADO(ID_EMPLEADO),
    foreign key (ID_PACIENTE) references PACIENTE(ID_PACIENTE),
    foreign key (ID_TRATAMIENTO_APLICADO) references TRATAMIENTO_APLICADO(ID_TRATAMIENTO),
    foreign key (ID_DIAGNOSTICO_SINTOMA) references DIAGNOSICO_SINTOMA(ID_DIAGNOSTICO),
    foreign key (ID_SINTOMA_PACIENTE) references SINTOMA_PACIENTE(ID_SINTOMA)
);

DROP TABLE EVALUACION;
DROP TABLE PACIENTE;
DROP TABLE EMPLEADO;
DROP TABLE SINTOMA_PACIENTE;
DROP TABLE TRATAMIENTO_APLICADO;
DROP TABLE DIAGNOSICO_SINTOMA;
DROP TABLE TITULO_EMPLEADO;
DROP TABLE GENERO;






